# Generated by Django 5.1.6 on 2025-02-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerifycodeMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('verify_code', models.CharField(max_length=4)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
