# Generated by Django 3.0.6 on 2025-03-04 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='課程名稱', max_length=255, unique=True, verbose_name='課程名稱')),
                ('introduction', models.TextField(help_text='課程介紹', verbose_name='課程介紹')),
                ('price', models.DecimalField(decimal_places=2, help_text='價格', max_digits=6, verbose_name='課程價格')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('teacher', models.ForeignKey(help_text='講師', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='講師')),
            ],
            options={
                'verbose_name': '課程訊息',
                'verbose_name_plural': '課程訊息',
                'ordering': ['price'],
            },
        ),
    ]
