"""
Django settings for myblog project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pv6z)qk&v#am8j2c(_0aokce#!+@e(l$1)i(80z7zso@n*@_9c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',
    'accounts'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myblog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # 配置模板資源文件夾路徑
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myblog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# 配置mysql資料庫
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 使用 mysql引擎
        'NAME':'blog_db',
        'USER':'root',
        'PASSWORD':'00000000',
        'HOST':'localhost',
        'PORT':'3306', 
        'OPTIONS': {
            'charset': 'utf8mb4'
        }
    }   
}
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# 配置靜態資源文件夾路徑
STATICFILES_DIRS = [BASE_DIR / 'static']

# # 設置重定向的登錄頁面 URL(即使用@login_required裝飾器保護的函數，如未登入會重定向到哪個頁面)
LOGIN_URL = 'accounts:login' # 如果有設定命名空間(account應用的 name=login 的url)
# # LOGIN_URL = 'accounts/login' # 如果沒有設定命名空間

# 媒體文件存儲路徑和URL
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Django 上傳的媒體(ex:圖片)文件應該存儲在哪個文件夾
MEDIA_URL = '/media/' # 通過哪個URL來訪問上傳的媒體文件


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 配置Django 後端 email設置

# gmail版本
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Gmail 的 SMTP 伺服器
EMAIL_PORT = 587  # TLS 通訊埠號
EMAIL_USE_TLS = True  # 啟用 TLS 加密
EMAIL_HOST_USER = 'hellendjango@gmail.com'  # 您的 Gmail 帳號
EMAIL_HOST_PASSWORD = 'xomd epey epbq hwcn'  # 應用程式密碼，保留空格

